# Generated by Django 4.2.7 on 2023-11-27 14:43

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to=webapp.models.user_directory_path, verbose_name='Изображения'),
        ),
    ]
